name: TempMOTD
author: ArkadSt
version: 1.0
main: org.arkadst.tempmotd.Main
api-version: 1.17

commands:
  tempmotd:
    description: "TempMOTD provided command."
    permission: tempmotd.admin
  setmotd:
    description: "TempMOTD provided command."
    usage: "§cUsage: /setmotd ROW(1 or 2) text"
    permission: tempmotd.admin

